language: ruby
sudo: false
cache: bundler
rvm:
  - 1.9.3
install:
  - bundle install --jobs=3 --retry=3 --deployment --path=${BUNDLE_PATH:-vendor/bundle}
  - bundle exec rake librarian:install
script:
  - bundle exec rake lint
  - bundle exec rake all_but_lint
